home/urls.py
from django.urls import path
from . import views


app_name = 'home'
urlpatterns = [
    path("", views.home, name="home"),
    path("signin/", views.signin, name="signin"),
    path("signout/", views.signout, name="signout"),
    path("users/", views.user_list, name="users"),
    path("users/create", views.user_create, name="user_create"),
    path("users/store", views.user_store, name="user_store"),
]

otromundo/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
]

home/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.

class User(AbstractUser):
    username = models.CharField(max_length=50, null=False, unique=True)
    rut = models.CharField(max_length=50,  null=True)
    email = models.EmailField(max_length=254,  null=False,  unique=True, )
    phone = models.CharField(max_length=15, null=True)
    birthday = models.DateField(null=True)
    created_at = models.DateTimeField(auto_now=False, auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True, auto_now_add=False)
    password = models.CharField(max_length=128, null=True)

    # def save(self, *args, **kwargs):
    #     self.username = self.email
    #     super().save(*args, **kwargs)

    # def __str__(self):
    #     return self.username

home/forms.py
from django import forms
from .models import User

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username','rut','first_name','last_name','email','phone','birthday']
        labels = {'Usuario':'username',
                  'RUT':'rut',
                  'Nombre':'first_name',
                  'Apellido':'last_name',
                  'Email':'email',
                  'Teléfono':'phone',
                  'Nacimiento':'birthday'}
        # extra_fields = ['field']

    def __init__(self, *args, **kwargs): #añadir clases a los campos del form
        super(UserForm, self).__init__(*args, **kwargs)
        for field_name in self.fields:
            self.fields[field_name].widget.attrs['class'] = 'form-control'

home/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required

from .models import User
from .forms import UserForm 

# Create your views here.
def home(request):
    context = {}
    return render(request, "home/home.html", context)

def signin(request):
    if request.method == 'GET':
        context = {'form': AuthenticationForm}
        return render(request, 'auth/signin.html', context)
    else:
        user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
        if user is None:
            context = {'form': AuthenticationForm, 'error' : 'El usuario o la contraseña son incorrectos'}
            return render(request, 'auth/signin.html', context)
        else:
            login(request, user)
            return redirect('home:home')

def signout(request):
    logout(request)
    return redirect('home:home')
""" def signup(request):
    signup_form = SignUpForm()
    context = {'form': signup_form}
    return render(request, 'signup.html', context) """

@login_required
def user_list(request):
    users = User.objects.all()
    context = {'users': users}
    return render(request, "user/index.html", context)

@login_required
def user_create(request):
    if request.method == 'GET':
        user_form = UserForm()
        context = {'user_form': user_form}
        return render(request, "user/create.html", context)
    else:
        return HttpResponse('Método no soportado')

@login_required
def user_store(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST)
        if user_form.is_valid():
            user_form.save()
            return redirect('home:users')
        else:
            return HttpResponse('El formulario no es válido')
    else:
        return HttpResponse('Método no soportado')

home/templates/home/home.html
{% extends '../layouts/base.html' %}
{% load static %}

{% block title %}Yo quiero otro mundo{% endblock title %}

{% block content %}

<div class="container bg-white bg-opacity-50 mt-4 mb-4">
    <div id="myCarousel" class="carousel slide mb-6" data-bs-ride="carousel">
        <div class="carousel-indicators">
          <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="" aria-label="Slide 1"></button>
          <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2" class=""></button>
          <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3" class="active" aria-current="true"></button>
        </div>
        <div class="carousel-inner">
          <div class="carousel-item">
            <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="var(--bs-secondary-color)"></rect></svg>
            <div class="container">
              <div class="carousel-caption text-start">
                <h1>Example headline.</h1>
                <p class="opacity-75">Some representative placeholder content for the first slide of the carousel.</p>
                <p><a class="btn btn-lg btn-primary" href="#">Sign up today</a></p>
              </div>
            </div>
          </div>
          <div class="carousel-item">
            <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="var(--bs-secondary-color)"></rect></svg>
            <div class="container">
              <div class="carousel-caption">
                <h1>Another example headline.</h1>
                <p>Some representative placeholder content for the second slide of the carousel.</p>
                <p><a class="btn btn-lg btn-primary" href="#">Learn more</a></p>
              </div>
            </div>
          </div>
          <div class="carousel-item active">
            <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="var(--bs-secondary-color)"></rect></svg>
            <div class="container">
              <div class="carousel-caption text-end">
                <h1>One more for good measure.</h1>
                <p>Some representative placeholder content for the third slide of this carousel.</p>
                <p><a class="btn btn-lg btn-primary" href="#">Browse gallery</a></p>
              </div>
            </div>
          </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>

    
      <!-- Marketing messaging and featurettes
      ================================================== -->
      <!-- Wrap the rest of the page in another container to center all the content. -->
    
      <div class="container marketing">
    
        <!-- Three columns of text below the carousel -->
        <div class="row">
          <div class="col-lg-4">
            <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="var(--bs-secondary-color)"></rect></svg>
            <h2 class="fw-normal">Heading</h2>
            <p>Some representative placeholder content for the three columns of text below the carousel. This is the first column.</p>
            <p><a class="btn btn-secondary" href="#">View details »</a></p>
          </div><!-- /.col-lg-4 -->
          <div class="col-lg-4">
            <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="var(--bs-secondary-color)"></rect></svg>
            <h2 class="fw-normal">Heading</h2>
            <p>Another exciting bit of representative placeholder content. This time, we've moved on to the second column.</p>
            <p><a class="btn btn-secondary" href="#">View details »</a></p>
          </div><!-- /.col-lg-4 -->
          <div class="col-lg-4">
            <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="var(--bs-secondary-color)"></rect></svg>
            <h2 class="fw-normal">Heading</h2>
            <p>And lastly this, the third column of representative placeholder content.</p>
            <p><a class="btn btn-secondary" href="#">View details »</a></p>
          </div><!-- /.col-lg-4 -->
        </div><!-- /.row -->
    
    
        <!-- START THE FEATURETTES -->
    
        <hr class="featurette-divider">
    
        <div class="row featurette">
          <div class="col-md-7">
            <h2 class="featurette-heading fw-normal lh-1">First featurette heading. <span class="text-body-secondary">It’ll blow your mind.</span></h2>
            <p class="lead">Some great placeholder content for the first featurette here. Imagine some exciting prose here.</p>
          </div>
          <div class="col-md-5">
            <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 500x500" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="var(--bs-secondary-bg)"></rect><text x="50%" y="50%" fill="var(--bs-secondary-color)" dy=".3em">500x500</text></svg>
          </div>
        </div>
    
        <hr class="featurette-divider">
    
        <div class="row featurette">
          <div class="col-md-7 order-md-2">
            <h2 class="featurette-heading fw-normal lh-1">Oh yeah, it’s that good. <span class="text-body-secondary">See for yourself.</span></h2>
            <p class="lead">Another featurette? Of course. More placeholder content here to give you an idea of how this layout would work with some actual real-world content in place.</p>
          </div>
          <div class="col-md-5 order-md-1">
            <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 500x500" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="var(--bs-secondary-bg)"></rect><text x="50%" y="50%" fill="var(--bs-secondary-color)" dy=".3em">500x500</text></svg>
          </div>
        </div>
    
        <hr class="featurette-divider">
    
        <div class="row featurette">
          <div class="col-md-7">
            <h2 class="featurette-heading fw-normal lh-1">And lastly, this one. <span class="text-body-secondary">Checkmate.</span></h2>
            <p class="lead">And yes, this is the last block of representative placeholder content. Again, not really intended to be actually read, simply here to give you a better view of what this would look like with some actual content. Your content.</p>
          </div>
          <div class="col-md-5">
            <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 500x500" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="var(--bs-secondary-bg)"></rect><text x="50%" y="50%" fill="var(--bs-secondary-color)" dy=".3em">500x500</text></svg>
          </div>
        </div>
    
        <hr class="featurette-divider">
    
        <!-- /END THE FEATURETTES -->
    
      </div><!-- /.container -->
    
    
      <!-- FOOTER -->

    

{% endblock content %}

home/templates/layouts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="h-100">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block styles %}{% endblock styles %}
    {% block scripts %}{% endblock scripts %}
    
    <link rel="icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}">
    <title>{% block title %}{% endblock title %}</title>
</head>
<body class="d-flex flex-column h-100">
    <header>
        {% include 'layouts/partials/navbar.html' %}
    </header>
    <main>
        {% block content %}{% endblock content %}
    </main>
    <footer class="mt-auto">
        {% include 'layouts/partials/footer.html' %}
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    
</body>
</html>

home/templates/layouts/partials/footer.html
{% load static %}
<div class="footer d-flex flex-wrap justify-content-between align-items-center px-4 py-3 border-top bg-light bg-opacity-25">
    <p class="col-md-4 mb-0 text-body-secondary">© 2023 Todos los derechos reservados</p>
    <a href="{% url 'home:home' %}" class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
        <img class="bi me-2 text-dark" src={% static "img/logo-black.svg" %} alt="Logo" width="40" height="32" >
    </a>
    <ul class="nav col-md-4 justify-content-end">
        <li class="nav-item">
            <a href="{% url 'home:home' %}" class="nav-link px-2 text-body-secondary">Inicio</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
            <a href="{% url 'home:users' %}" class="nav-link px-2 text-body-secondary">Usuarios</a>
        </li>
        {% if user.is_superuser %}
        <li class="nav-item">
            <a href="{% url 'admin:index' %}" class="nav-link px-2 text-body-secondary">Administración</a>
        </li>
        {% endif %}
        <li class="nav-item">
            <a href="{% url 'home:signout' %}" class="nav-link px-2 text-body-secondary">Log Out</a>
        </li>
        {% else %}
        <li class="nav-item">
            <a href="{% url 'home:signin' %}" class="nav-link px-2 text-body-secondary">Log In</a>
        </li>
        {% endif %}
    </ul>
</div>

home/templates/layouts/partials/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark px-3 bg-secondary bg-opacity-50">
    <div class="container-fluid">
        <a class="navbar-brand " href="{% url 'home:home' %}">
            <img src={% static "img/logo.svg" %} alt="" width="35" height="35" class="d-inline-block align-text-top logo">
            Yo quiero otro mundo
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarNav">
            <div class="ms-auto me-2 text-white">
                {% if user.is_authenticated %}
                <div class="bg-secondary bg-opacity-25 p-2 rounded">
                    Bienvenido
                        {% if user.first_name != "" %} {{user.first_name}} {{user.last_name}}
                        {% else %} {{user.username}}
                        {% endif %}
                    </div>
                {% endif %}
            </div>
            <div class=" bg-secondary bg-opacity-25 rounded p-0 m-0">
                <ul class="navbar-nav">
                    <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'home:home' %}">Inicio</a>
                    </li>
                    {% if user.is_authenticated %}
                    <hr class="vhr">
                    <li class="nav-item">
                    <a class="nav-link" href="{% url 'home:users' %}">Usuarios</a>
                    </li>
                    {% if user.is_superuser %}
                    <hr class="vhr">
                    <li class="nav-item">
                    <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                    </li>
                    {% endif %}
                    <hr class="vhr">
                    <li class="nav-item">
                    <a class="nav-link" href="{% url 'home:signout' %}">Log Out</a>
                    </li>
                    {% else %}
                    <hr class="vhr">
                    <li class="nav-item">
                    <a class="nav-link" href="{% url 'home:signin' %}">Log In</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</nav>

home/templates/user/create.html
{% extends '../layouts/base.html' %}
{% load static %}

{% block title %}Crear nuevo usuario{% endblock title %}

{% block content %}

<div class="container mt-4 mb-4">
    <div class="card ">
        <form class="form" action="{% url 'home:user_store' %}" method="POST">
        {% csrf_token %}
        <div class="card-header d-flex justify-content-between align-items-center bg-secondary bg-opacity-25">
            <h1 class="align-middle section-title"><img class="m-0 py-0" src="{% static 'img/users-icon.svg'%}" width="40" height="40">Crear nuevo usuario</h1>
        </div>
        <div class="card-body bg-opacity-25 p-4">
            {% for field in user_form %}
            <div class="mb-3">
                <label for="{{field.id_for_label}}" class="form-label">{{field.label}}</label>
                <p>{{field}}</p>
                <div id="{{field.name}}Help" class="form-text">{{ field.help_text }}</div>
            </div>
            {% endfor %}
            </div>
            <div class="card-footer">
                <button class="btn btn-primary" type="submit">Enviar</button>
            </div>
        </form>
    </div>
</div>


{% endblock content %}

home/templates/user/index.html
{% extends '../layouts/base.html' %}
{% load static %}

{% block title %}Yo quiero otro mundo{% endblock title %}

{% block content %}

<div class="container mt-4 mb-4">

    <div class="card">
        <div class="card-header d-flex justify-content-between align-items-center bg-secondary bg-opacity-25">
            <h1 class="align-middle section-title"><img class="m-0 py-0" src="{% static 'img/users-icon.svg'%}" width="40" height="40"> Usuarios</h1>
            <a class="btn btn-outline-primary justify-center " href="{% url 'home:user_create' %}">+</a>
        </div>
        <div class="card-body bg-secondary-subtle bg-opacity-25 p-0">
            <table class="table table-striped table-hover">
                <thead class="table-secondary">
                    <tr>
                        <th scope="col">Nombre de usuario</th>
                        <th scope="col">RUT</th>
                        <th scope="col">Nombre</th>
                        <th scope="col">Apellido</th>
                        <th scope="col">Correo Electrónico</th>
                        <th scope="col">Teléfono</th>
                    </tr>
                </thead>
                <tbody>
                    {% for user in users %}
                    <tr>
                        <td>{{user.username}}</td>
                        <td>{{user.rut}}</td>
                        <td>{{user.first_name}}</td>
                        <td>{{user.last_name}}</td>
                        <td>{{user.email}}</td>
                        <td>{{user.phone}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock content %}